export const venues = [
    {
      id: '1',
      name: 'Akmami Hotel Jakarta',
      location: 'South Jakarta',
      image: '/assets/images/bg.png',
      price: 'Rp 2.100.000',
      reviews: '4,6/5.0 Reviews',
    },
    {
      id: '2',
      name: 'Grand Bali Resort',
      location: 'Bali',
      image: '/assets/images/bg.png',
      price: 'Rp 1.800.000',
      reviews: '4,8/5.0 Reviews',
    },
    {
      id: '3',
      name: 'Surabaya Luxury Hotel',
      location: 'Surabaya',
      image: '/assets/images/bg.png',
      price: 'Rp 1.500.000',
      reviews: '4,5/5.0 Reviews',
    },
    {
      id: '4',
      name: 'Medan City Hotel',
      location: 'Medan',
      image: '/assets/images/bg.png',
      price: 'Rp 1.200.000',
      reviews: '4,2/5.0 Reviews',
    },
    {
      id: '5',
      name: 'Jakarta Plaza Hotel',
      location: 'Central Jakarta',
      image: '/assets/images/bg.png',
      price: 'Rp 2.400.000',
      reviews: '4,7/5.0 Reviews',
    },
    {
      id: '6',
      name: 'Bandung Hill Resort',
      location: 'Bandung',
      image: '/assets/images/bg.png',
      price: 'Rp 1.950.000',
      reviews: '4,9/5.0 Reviews',
    },
    {
      id: '7',
      name: 'Yogyakarta Heritage Hotel',
      location: 'Yogyakarta',
      image: '/assets/images/bg.png',
      price: 'Rp 1.700.000',
      reviews: '4,3/5.0 Reviews',
    },
    {
      id: '8',
      name: 'Surabaya Oceanfront Hotel',
      location: 'Surabaya',
      image: '/assets/images/bg.png',
      price: 'Rp 1.800.000',
      reviews: '4,6/5.0 Reviews',
    },
    {
      id: '9',
      name: 'Ubud Green Villa',
      location: 'Ubud, Bali',
      image: '/assets/images/bg.png',
      price: 'Rp 3.000.000',
      reviews: '5.0/5.0 Reviews',
    },
    {
      id: '10',
      name: 'Seminyak Beach Resort',
      location: 'Bali',
      image: '/assets/images/bg.png',
      price: 'Rp 2.800.000',
      reviews: '4,8/5.0 Reviews',
    },
    {
      id: '11',
      name: 'Medan Grand Palace',
      location: 'Medan',
      image: '/assets/images/bg.png',
      price: 'Rp 1.500.000',
      reviews: '4,4/5.0 Reviews',
    },
    {
      id: '12',
      name: 'Makassar Royal Hotel',
      location: 'Makassar',
      image: '/assets/images/bg.png',
      price: 'Rp 1.600.000',
      reviews: '4,5/5.0 Reviews',
    },
    {
      id: '13',
      name: 'Bali Skyview Hotel',
      location: 'Bali',
      image: '/assets/images/bg.png',
      price: 'Rp 2.200.000',
      reviews: '4,6/5.0 Reviews',
    },
    {
      id: '14',
      name: 'Surabaya Business Inn',
      location: 'Surabaya',
      image: '/assets/images/bg.png',
      price: 'Rp 1.900.000',
      reviews: '4,5/5.0 Reviews',
    },
    {
      id: '15',
      name: 'Jakarta Cityview Hotel',
      location: 'Jakarta',
      image: '/assets/images/bg.png',
      price: 'Rp 2.300.000',
      reviews: '4,7/5.0 Reviews',
    },
  ];
  